### ISSUE TITLE
Setup CI for this repo

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Persistence.EventStore#4]
Need to get some CI in place for this repo. Usually we follow the template defined here: https://github.com/petabridge/petabridge-dotnet-new

**Comment by ptjhuang** [comment]
I might need some tips on this - is there an account on Azure devops that builds all these contrib projects at the moment like akka.net core?

Also re. unit tests - it needs to spin up EventStore container before tests, does Azure devops support this?
