### ISSUE TITLE
recreating deleted streams

### ISSUE THREAD

**Issue by Zetanova** [akkadotnet/Akka.Persistence.EventStore#6]
To take the SequenceNumber from the metadata.StreamMetadata.TruncateBefore is not correct,
On stream delete the EventStore admin interface is setting the TruncateBefore value to Int64.MaxValue 

I made a workaround under 
https://github.com/Zetanova/Akka.Persistence.EventStore/commit/572eb6a4be671b89617c836ec6a291b7c749bb23

and will make a PR when i resolved the issue to load the last deleted event:
https://github.com/EventStore/EventStore/issues/1845

**Comment by mjaric** [comment]
@Zetanova  is this still valid? Should I merge pull request?

**Comment by Zetanova** [comment]
It's still valid, but it is only a poor workaround
the solution would be to load the last deleted message 
of the stream and the sequenceId from the metadata. 

I didn't found on the first look how the eventstore webinterface
is loading this spezial message, i couldnt find anything to load the last-deleted 
message witht he dotnet-client too.

**Comment by Zetanova** [comment]
With feedback from the eventstore team
the optimal solution would be instead of deleting te events 
to write a own tombstone with $tb : current- 1 (deleting by default does $tb : current).
This own tombstone could still incode the normal metadata with the last SeqNr.

source:
https://github.com/EventStore/EventStore/issues/1845#issuecomment-540698027

**Comment by ismaelhamed** [comment]
@Zetanova despite the feedback, is there any other reason why using `StreamEventSlice.LastEventNumber` when the stream's status is `StreamNotFound` is not a valid way to solve this?

**Comment by Zetanova** [comment]
@ismaelhamed EventStream EventNumber is not the akka SeqNr

**Comment by ismaelhamed** [comment]
@Zetanova I'll give it another look because I'm really interested in this plugin but, AFAICS, in case of a soft deleted stream (`StreamNotFound`) we could probably just return `0L` as the `sequenceNr`. You're not allowed to recover any previous events from the stream anyway, so it'll work like if you've manually deleted all the events for a `PersistenceId` in SQL.

**Comment by Zetanova** [comment]
@ismaelhamed this will not work, because of the snapshot store

**Comment by SeanFarrow** [comment]
Hi,

I just came across this.

I could be wrong, but if a stream is deleted, then surely the snapshots that apply to that stream are no longer valid?

**Comment by Zetanova** [comment]
@SeanFarrow Logically yes, but they are in a separate stream or even store engine, the snapshot itself contains the event-seqNr 
and is used start number. 

Best practice to delete a stream is to 
first add a own deleted/flushed event message to the stream 
and then delete all events before this message.

**Comment by SeanFarrow** [comment]
Exactly, the deletion of snapshots that will never be recoverable is the missing piece here.
